### ISSUE TITLE
In a CBV how do you override the extra_data?

### ISSUE THREAD

**Issue by rfc791** [pinax/pinax-eventlog#16]
I can't get the override of the extra_data property to work on a CBV view.  It complains about view object is not JSON serializable.

This is what I am trying to do to override it.

     class  ApplicationUpdateView(EventLogMixin, UpdateView):
         ....
         def extra_data(self):      
             return super(ApplicationUpdateView, self).extra_data({"TEST": "TEST"})

**Comment by jacobwegner** [comment]
@rfc791:  You'd want to override the property like so:

```
    class ApplicationUpdateView(EventLogMixin, UpdateView):
        ....
        @property
        def extra_data(self):
            # build up dict as desired
            return {
                "TEST": "TEST"
            }
```

**Comment by rfc791** [comment]
Thanks for getting back to me so fast.  So when I try that I get the same Exception.

<bound method ApplicationUpdate.extra_data of <applications.views.ApplicationUpdate object at 0x7f45f277b390>> is not JSON serializable

**Comment by jacobwegner** [comment]
The base implementation of the `extra_data` returns an empty dictionary.

If you want to override it by inheriting from `EventLogMixin`, that would look like:

```
class MyObjUpdateView(EventLogMixin, UpdateView):
    form_class = MyObjUpdateForm
    action_kind = "UPDATED"

    ...

    @property
    def extra_data(self):
        extra_data = super(MyObjUpdateView, self).extra_data
        extra_data.update({
            "repo": "pinax-eventlog"
        })
        return extra_data
```

Have you been able to get your view to working with `EventLogMixin` without overriding `extra_data` (just logging the action and user)?

**Comment by rfc791** [comment]
That did it.  Thanks a lot.  I really like the simplicity of this.  Great tool.

**Comment by jacobwegner** [comment]
@rfc791 that's great to hear!
