### ISSUE TITLE
eventlog models has changed to support Mysql?

### ISSUE THREAD

**Issue by patrickscottbest** [pinax/pinax-eventlog#30]
We are finding it difficult to use this in our Mysql-based project because of the reliance in release 3.0.1 because of the reliance on django.contrib.postgres.fields to define the "extra" field.

When will the next release on pypi be?

**Comment by KatherineMichel** [comment]
@patrickscottbest I've asked the people about me about getting these published. I don't have a direct access to PyPI at the moment for all of these, unfortunately.

**Comment by patrickscottbest** [comment]
We've found the workaround and have contributed the solution to the Pinax community.  Thanks for your good work @KatherineMichel !  See you on the slack.
