### ISSUE TITLE
Support Django 2.2 via django-jsonfield-backport

### ISSUE THREAD

**Issue by jacobwegner** [pinax/pinax-eventlog#34]
As discussed in #32, #33 drops Django 2.2 support.

Since Django 2.2 is an LTS release, the co-author of the new JSONField added in 3.1 actually created a backport package:

https://github.com/laymonage/django-jsonfield-backport#why-create-another-one

> Django's release process does not backport new features to previous feature releases. However, the current LTS release is 2.2 which is still supported until April 2022. The next LTS release is Django 3.2 in April 2021 that happens to be the end of extended support for Django 3.1.
>
> Some projects only use LTS releases of Django. There are also incompatibilities between Django 3.0 and 3.1. Therefore, using Django 3.1 may not be an option for some people at the moment
>
> Since JSONField seems to be in popular demand and that it works well as a standalone package, I decided to create a backport.

I'd like to propose we introduce a small shim to the 5.x release that:
- adds django-jsonfield-backport as an optional dependency
- modifies `models.py` and the initial migration to work with the shim'd field
- provides documentation to site developers on how to use `eventlog` in Django~2.2 projects via django-jsonfield-backport

As part of this work, we would update the `tox` test matrix to prove out this support.

@paltman and @KatherineMichel: Does this seem reasonable to you?  This would allow us to leverage the awesome JSONField while still keeping Django 2.2 compatibility as outlined in https://github.com/pinax/pinax/wiki/Pinax-20.XX-Release-Plan#pinax-20xx-release-overview.

If so, I can prepare a PR within the next week or so.

Thanks!

**Comment by paltman** [comment]
Sounds great!

**Comment by KatherineMichel** [comment]
@jacobwegner Awesome, thank you!
