### ISSUE TITLE
django-jsonfield vs jsonfield

### ISSUE THREAD

**Issue by dmr** [pinax/pinax-eventlog#4]
I would like to use jsonfield instead of django-jsonfield which works fine once it is installed but when I install eventlog after I installed jsonfield django-jsonfield will overwrite the package. This is more of a django-jsonfield issue but I was wondering if maybe eventlog could provide an option to install jsonfield instead of django-jsonfield.

I think I would change the setup.py to include an "extra" option to use jsonfield instead. What do you think?

**Comment by ossanna16** [comment]
Any further discussion on this?

**Comment by rizumu** [comment]
@paltman Since Django 1.9 now has a built in jsonfield, so that should be used going forward. Probably we should close and begin updating any apps to use the 1.9 built-in with a ported fallback for < 1.9?

**Comment by aijogja** [comment]
Related to jsonfield. How to use query filter by jsonfield?
I need to query log data that `extra` field contains `"title":"ADDED"`. Is it possible?

Thanks

**Comment by paltman** [comment]
eventlog is now using `jsonfield`
